chain = "mainnet"
# datadir = "$DATA_DIR"
syncmode = "full"

[jsonrpc]
# ipcpath = "$DATA_DIR/bor.ipc"

[jsonrpc.http]
enabled = true
host = "127.0.0.1"
vhosts = ["*"]
corsdomain = ["*"]
port = 8545
api = ["eth", "net", "web3", "txpool", "bor"]

[p2p]
port = 30303
maxpeers = 200

[miner]
gasceil = 20000000
gasprice = "30000000000"

[telemetry]
metrics = true

[txpool]
accountqueue = 16
accountslots = 16
globalqueue = 32768
globalslots = 32768
lifetime = "1h30m0s"
nolocals = true
pricelimit = 30000000000
