# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### RPC and REST configs #####

# RPC endpoint for ethereum chain
eth_rpc_url = "https://goerli.infura.io/v3/<YOUR_INFURA_KEY>"

# RPC endpoint for bor chain
bor_rpc_url = "http://localhost:8545"

# RPC endpoint for tendermint
tendermint_rpc_url = "http://0.0.0.0:26657"

# Heimdall REST server endpoint
heimdall_rest_server = "http://0.0.0.0:1317" 

#### Bridge configs ####

# MQTT endpoint
amqp_url = "amqp://guest:guest@localhost:5672/" 

## Bridge Poll Intervals 
checkpoint_poll_interval = "5m0s" 
syncer_poll_interval = "1m0s"
noack_poll_interval = "16m50s"
clerk_poll_interval = "10s" 
span_poll_interval = "1m0s"

#### gas limits ####
main_chain_gas_limit = "5000000"

##### Timeout Config #####
no_ack_wait_time = "30m0s"

